import '@/styles/globals.css'
import Head from './head'
import Header from './Header'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <Head />

      <body className='w-screen h-full'>
        <Header />
        
          {children}
        
        
      </body>
    </html>
  )
}
